




name: nfc_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-333.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  permission_handler: ^10.4.3
  flutter_bloc: ^8.1.3
  localstorage: ^4.0.1+4
  
  alt_sms_autofill: ^1.0.0
  flutter_nfc_kit: ^3.3.1
  background_sms: ^0.0.4
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/gif/
    - assets/images/img/
    - assets/images/svg/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 500
    # - family:  NewIcons
    #   fonts:
    #     - asset: assets/icons/fonts/NewIcons.ttf

# this tool generate a logo aplication
# Execute this comand: flutter pub run flutter_launcher_icons:main 
flutter_icons:
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#FFFFFF"
  ios: true
  android: true

# this tool generate a splash screen aplication 
# Execute this comand: flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: "assets/logo/logo.png"
  color: "#FFFFFF"
  image_dark: "assets/logo/logo.png"
  color_dark: "#000000"
  android: true
  ios: true

# this tool generate i18 aplicationtion class  
# Excuute this comand: 
flutter_intl:
  enabled: true # Only true when you change the intl files 
  main_locale: es
  class_name: AppLocalisations


#svg atributes 
# https://undraw.co/search
# https://www.svgbackgrounds.com/

#New Icons
# https://www.fluttericon.com/